#!/bin/sh
# Lazy shim for pip using mise (pip is bundled with python)

echo "[Shim] pip requested. Bootstrapping mise and installing python globally..." >&2

mise use -g python@latest

exec mise exec -- pip "$@"
